#Overworld Geodes properties file
#Mon Jun 29 03:59:58 JST 2026
shouldGenerateRedstoneGeodes=true
shouldGenerateLapisGeodes=true
shouldGeneratePinkTopazGeodes=true
shouldGeneratePrismarineGeodes=true
shouldGenerateEchoGeodes=true
shouldGenerateCelestiteGeodes=true
shouldGenerateDiamondGeodes=true
shouldGenerateEmeraldGeodes=true
